/*
  # Add Superlative Game Support

  ## Summary
  Creates a dedicated table structure for the Superlative game ("Which is bigger/heavier/older?"),
  replacing the previous JSONB metadata approach with proper relational tables that support
  easy content management including image uploads.

  ## New Tables

  ### `superlative_puzzles`
  - `id` - Primary key
  - `game_id` - FK to games table
  - `comparison_type` - e.g. "Longer", "Heavier", "Older", "Taller", "Faster", "Wider"
  - `correct_answer` - Name of the winning item
  - `reveal_note` - Text shown after answer (e.g. "The Nile is 6,650 km long")
  - `difficulty` - easy / medium / hard
  - `is_active` - Whether this puzzle is available for play
  - `created_at`

  ### `superlative_items`
  - `id` - Primary key
  - `puzzle_id` - FK to superlative_puzzles
  - `role` - 'anchor' or 'challenger' (which side of the comparison)
  - `name` - Display name of the item
  - `tagline` - Optional short descriptor
  - `value` - Numeric value for the comparison
  - `unit` - Unit label (e.g. "km", "kg", "years")
  - `image_url` - URL to item image (external or Supabase storage)
  - `created_at`

  ## Modified Tables

  ### `playlist_rounds`
  - Added `superlative_puzzle_id` column as nullable FK to `superlative_puzzles`

  ### `puzzles` (game_type constraint)
  - Added 'superlative' as valid game_type value

  ## Security
  - RLS enabled on both new tables
  - Public read access for authenticated and anonymous users (content is not user-specific)
  - No insert/update/delete policies for end users (admin-only via service role)
*/

-- ── superlative_puzzles ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS superlative_puzzles (
  id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_id     bigint REFERENCES games(id),
  comparison_type text NOT NULL CHECK (comparison_type = ANY (ARRAY[
    'Longer', 'Wider', 'Heavier', 'Older', 'Taller', 'Faster', 'Bigger', 'Deeper', 'Hotter'
  ])),
  correct_answer  text NOT NULL,
  reveal_note     text,
  difficulty      text DEFAULT 'medium' CHECK (difficulty = ANY (ARRAY['easy', 'medium', 'hard'])),
  is_active       boolean DEFAULT true,
  created_at      timestamptz DEFAULT now()
);

ALTER TABLE superlative_puzzles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active superlative puzzles"
  ON superlative_puzzles FOR SELECT
  USING (is_active = true);

-- ── superlative_items ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS superlative_items (
  id          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  puzzle_id   bigint NOT NULL REFERENCES superlative_puzzles(id) ON DELETE CASCADE,
  role        text NOT NULL CHECK (role = ANY (ARRAY['anchor', 'challenger'])),
  name        text NOT NULL,
  tagline     text,
  value       numeric NOT NULL,
  unit        text NOT NULL,
  image_url   text,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE superlative_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read superlative items"
  ON superlative_items FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM superlative_puzzles sp
      WHERE sp.id = superlative_items.puzzle_id
        AND sp.is_active = true
    )
  );

-- ── playlist_rounds: add superlative FK ──────────────────────────────────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'playlist_rounds'
      AND column_name = 'superlative_puzzle_id'
  ) THEN
    ALTER TABLE playlist_rounds
      ADD COLUMN superlative_puzzle_id bigint REFERENCES superlative_puzzles(id);
  END IF;
END $$;

-- ── puzzles: allow 'superlative' game_type ───────────────────────────────────

ALTER TABLE puzzles DROP CONSTRAINT IF EXISTS puzzles_game_type_check;

ALTER TABLE puzzles ADD CONSTRAINT puzzles_game_type_check
  CHECK (game_type = ANY (ARRAY[
    'multiple_choice', 'disordat', 'ranking', 'photo_mystery',
    'fake_out', 'hive_mind', 'double_fake', 'superlative'
  ]));

-- ── indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_superlative_puzzles_game_id ON superlative_puzzles(game_id);
CREATE INDEX IF NOT EXISTS idx_superlative_items_puzzle_id ON superlative_items(puzzle_id);
CREATE INDEX IF NOT EXISTS idx_playlist_rounds_superlative_puzzle_id ON playlist_rounds(superlative_puzzle_id);
